server:
  port: 8085
  servlet:
    context-path: /Comment
logging:
  level:
    root: INFO
    com.example.myapp: DEBUG
  file:
    name: logs/myapp.log
spring:
  datasource:
    username: root
    password: ZQH123321!
    url: jdbc:mysql://localhost:3306/Comment
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:MapperXML/**/*Mapper.xml